### ISSUE TITLE
Invalid Vimeo URL causes TypeError in player.es.js

### ISSUE THREAD

**Issue by JaykrishnaArhamlabs** [vimeo/player.js#1038]
### Expected Behavior
The Vimeo player should validate the URL before attempting to load it. If the URL is invalid, an appropriate error message should be logged, and the user should be informed without the script crashing.

### Actual Behavior
When an valid Vimeo URL is provided, after the onChange on list of items with valid vimeo urls , the following error is thrown:
Uncaught (in promise) TypeError: The url must be a valid Vimeo url.
    at player.es.js:1255:1
    at Array.forEach (<anonymous>)
    at processData (player.es.js:1254:1)
    at _this._onMessage (player.es.js:2168:1)

### Steps to Reproduce
1. Provide a list of Vimeo URLs where some URLs are all valid.
2. Attempt to load these URLs using the Vimeo player.
3. Click or change the item to trigger the player loading.

Package Version:
    "@u-wave/react-vimeo": "^0.9.10",
    "@vimeo/player": "^2.23.0",

Temporary Solution:
Adding a setTimeout in the onChange event to reload or update the player component using a React hook like useState.

**Comment by rkrishnan8594** [comment]
Hi @JaykrishnaArhamlabs - can you provide a CodePen or JSFiddle (or some other test page) where this issue can be reproduced? It's not clear to me what the issue is with the URL validation that is already performed.

**Comment by iangoodall** [comment]
Hi @rkrishnan8594. We are having the same issue because we created a little app that shows different videos and their chapters. Noticed that it stopped working yesterday with the same error. Occurs when we use the loadVideo() function with the URL that is supplied from the share link in Vimeo.

Here is a Codepen of the issue in isolation for us. You can see it loads the originally linked video but the error is thrown in the console after loadVideo() is called.

[Codepen of the issue.](https://codepen.io/iangoodall/pen/GRaGvKZ)

**Comment by Ihor-Karpyn** [comment]
There is an example of an issue. Please take a look.

[code sandbox](https://codesandbox.io/p/sandbox/codepen-with-react-forked-m7lpjt?file=%2Fsrc%2Fcomponents%2FApp.js)

![2024-06-25 15 49 26](https://github.com/vimeo/player.js/assets/63306833/c84c9e5b-03ba-4737-870c-47554f1ed583)

![2024-06-25 15 49 49](https://github.com/vimeo/player.js/assets/63306833/950c7e9b-439c-4769-a353-9e9bf2a90352)


CC @rkrishnan8594

**Comment by iangoodall** [comment]
> There is an example of an issue. Please take a look.
> 
> [code sandbox](https://codesandbox.io/p/sandbox/codepen-with-react-forked-m7lpjt?file=%2Fsrc%2Fcomponents%2FApp.js)
> 
> ![2024-06-25 15 49 26](https://private-user-images.githubusercontent.com/63306833/342733559-c84c9e5b-03ba-4737-870c-47554f1ed583.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTY3NzgsIm5iZiI6MTcxOTM1NjQ3OCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NTktYzg0YzllNWItMDNiYS00NzM3LTg3MGMtNDc1NTRmMWVkNTgzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDIzMDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMzBhY2Y4M2U0MDMzYTQ5OGUxZTJjNTJhNjZmNTA3YmZlZjcwZmM0OTgxOGU0ZWYzZjU4YWUyZjA0YmRjYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9AWwvzNXqRt0bGBB6IlEZQTW2OryHcJvsW2jwjnCD74) [ ![2024-06-25 15 49 26](https://private-user-images.githubusercontent.com/63306833/342733559-c84c9e5b-03ba-4737-870c-47554f1ed583.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTY3NzgsIm5iZiI6MTcxOTM1NjQ3OCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NTktYzg0YzllNWItMDNiYS00NzM3LTg3MGMtNDc1NTRmMWVkNTgzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDIzMDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMzBhY2Y4M2U0MDMzYTQ5OGUxZTJjNTJhNjZmNTA3YmZlZjcwZmM0OTgxOGU0ZWYzZjU4YWUyZjA0YmRjYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9AWwvzNXqRt0bGBB6IlEZQTW2OryHcJvsW2jwjnCD74) ](https://private-user-images.githubusercontent.com/63306833/342733559-c84c9e5b-03ba-4737-870c-47554f1ed583.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTY3NzgsIm5iZiI6MTcxOTM1NjQ3OCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NTktYzg0YzllNWItMDNiYS00NzM3LTg3MGMtNDc1NTRmMWVkNTgzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDIzMDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMzBhY2Y4M2U0MDMzYTQ5OGUxZTJjNTJhNjZmNTA3YmZlZjcwZmM0OTgxOGU0ZWYzZjU4YWUyZjA0YmRjYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9AWwvzNXqRt0bGBB6IlEZQTW2OryHcJvsW2jwjnCD74) [ ](https://private-user-images.githubusercontent.com/63306833/342733559-c84c9e5b-03ba-4737-870c-47554f1ed583.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTY3NzgsIm5iZiI6MTcxOTM1NjQ3OCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NTktYzg0YzllNWItMDNiYS00NzM3LTg3MGMtNDc1NTRmMWVkNTgzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDIzMDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMzBhY2Y4M2U0MDMzYTQ5OGUxZTJjNTJhNjZmNTA3YmZlZjcwZmM0OTgxOGU0ZWYzZjU4YWUyZjA0YmRjYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9AWwvzNXqRt0bGBB6IlEZQTW2OryHcJvsW2jwjnCD74)
> 
> ![2024-06-25 15 49 49](https://private-user-images.githubusercontent.com/63306833/342733574-950c7e9b-439c-4769-a353-9e9bf2a90352.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTY3NzgsIm5iZiI6MTcxOTM1NjQ3OCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NzQtOTUwYzdlOWItNDM5Yy00NzY5LWEzNTMtOWU5YmYyYTkwMzUyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDIzMDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NmI2ZDJkYmVjMjdhMDZjMjE2YWI3MTU0NDY4MDZlYzczNjdiOTQ4NzE3YjVjNDdlZTYyNDcxMzQ0NDhhODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.716-2w_q3EBxQKIT_U7tC1NVN69jVErDH-k24oB0prU) [ ![2024-06-25 15 49 49](https://private-user-images.githubusercontent.com/63306833/342733574-950c7e9b-439c-4769-a353-9e9bf2a90352.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTY3NzgsIm5iZiI6MTcxOTM1NjQ3OCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NzQtOTUwYzdlOWItNDM5Yy00NzY5LWEzNTMtOWU5YmYyYTkwMzUyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDIzMDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NmI2ZDJkYmVjMjdhMDZjMjE2YWI3MTU0NDY4MDZlYzczNjdiOTQ4NzE3YjVjNDdlZTYyNDcxMzQ0NDhhODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.716-2w_q3EBxQKIT_U7tC1NVN69jVErDH-k24oB0prU) ](https://private-user-images.githubusercontent.com/63306833/342733574-950c7e9b-439c-4769-a353-9e9bf2a90352.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTY3NzgsIm5iZiI6MTcxOTM1NjQ3OCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NzQtOTUwYzdlOWItNDM5Yy00NzY5LWEzNTMtOWU5YmYyYTkwMzUyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDIzMDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NmI2ZDJkYmVjMjdhMDZjMjE2YWI3MTU0NDY4MDZlYzczNjdiOTQ4NzE3YjVjNDdlZTYyNDcxMzQ0NDhhODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.716-2w_q3EBxQKIT_U7tC1NVN69jVErDH-k24oB0prU) [ ](https://private-user-images.githubusercontent.com/63306833/342733574-950c7e9b-439c-4769-a353-9e9bf2a90352.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTY3NzgsIm5iZiI6MTcxOTM1NjQ3OCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NzQtOTUwYzdlOWItNDM5Yy00NzY5LWEzNTMtOWU5YmYyYTkwMzUyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDIzMDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NmI2ZDJkYmVjMjdhMDZjMjE2YWI3MTU0NDY4MDZlYzczNjdiOTQ4NzE3YjVjNDdlZTYyNDcxMzQ0NDhhODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.716-2w_q3EBxQKIT_U7tC1NVN69jVErDH-k24oB0prU)
> 
> CC @rkrishnan8594

Thanks for creating these GIF they illustrate the issue perfectly :)

**Comment by iangoodall** [comment]
To add more clarity here, it also occurs in the [Vimeo API Demo.](https://player.vimeo.com/api/demo/)

Here's a screenshot after I've put in the URL to the video which is https://vimeo.com/864270837

![Screenshot 2024-06-26 at 8 23 02 AM](https://github.com/vimeo/player.js/assets/34199235/63c65989-e6f4-4c08-90f6-88a2088eaba1)

**Comment by rkrishnan8594** [comment]
Hi all - thanks for reporting this issue. While we work on deploying a fix, my recommendation would be to provide video IDs or player.vimeo.com/video/12345678 URLs to the `loadVideo()` method, as these are officially supported argument types.

**Comment by rkrishnan8594** [comment]
This issue should now be fixed.

**Comment by iangoodall** [comment]
Hi @rkrishnan8594 , just wanted to note that your previous comment before the issue is marked as fixed mentioned using the URL format player.vimeo.com/video/12345678 for example. We implemented this as a fix on our end and now since you've marked this issue as fixed, our fix which changed our use of the standard URL to the player URL is no longer working. This is occurring on the [Vimeo Player API demo site](https://player.vimeo.com/api/demo/)

For our video https://player.vimeo.com/video/545813409 for example, it works now on the API site with https://vimeo.com/545813409 but throws the error when I use the player URL. I've taken a screenshot to demonstrate.

<img width="1031" alt="Screenshot 2024-06-29 at 2 46 17 AM" src="https://github.com/vimeo/player.js/assets/34199235/711c4f84-be7a-42c8-bda6-b72239aa8983">

**Comment by hoopsalytics** [comment]
Also still broken for me. Using player.js to load a video like this:
https://player.vimeo.com/video/912088535?h=37366bc1ae

**Comment by arturor1990** [comment]
same problem here with all the videos on my app (this one for example  https://player.vimeo.com/video/935732439?h=88bdbf3431) TypeError: The url must be a valid Vimeo url.

**Comment by iangoodall** [comment]
> This issue should now be fixed.

Hi @rkrishnan8594, the issue appeared fix for a while and the above comments were correct that using the https://player.vimeo.com/video/123456789 style of link did not, but when I checked today the issue as originally reported is back.

**Comment by rkrishnan8594** [comment]
Hey all - we should be fully back in a good state now. I tested this morning on an [embed URL](https://player.vimeo.com/video/912088535?h=37366bc1ae), a [Vimeo URL](https://vimeo.com/864270837), and a video ID. Please let me know if you observe any other issues. Thank you!

**Comment by JaykrishnaArhamlabs** [comment]
> There is an example of an issue. Please take a look.
> 
> [code sandbox](https://codesandbox.io/p/sandbox/codepen-with-react-forked-m7lpjt?file=%2Fsrc%2Fcomponents%2FApp.js)
> 
> ![2024-06-25 15 49 26](https://private-user-images.githubusercontent.com/63306833/342733559-c84c9e5b-03ba-4737-870c-47554f1ed583.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTkyOTAsIm5iZiI6MTcxOTk5ODk5MCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NTktYzg0YzllNWItMDNiYS00NzM3LTg3MGMtNDc1NTRmMWVkNTgzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA5Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MTZkNjBjYTY2MzNjNjJhMzRjNzIyNWViMzk5ODg0OTcyYTYxMjc4Yzc5MjIyNjRiMWNiNWM0M2UxZjE0YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hoq1CLY53Ubc7CQI0HnhiNbQlL50-mhCACxxJCHgbVI) [ ![2024-06-25 15 49 26](https://private-user-images.githubusercontent.com/63306833/342733559-c84c9e5b-03ba-4737-870c-47554f1ed583.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTkyOTAsIm5iZiI6MTcxOTk5ODk5MCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NTktYzg0YzllNWItMDNiYS00NzM3LTg3MGMtNDc1NTRmMWVkNTgzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA5Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MTZkNjBjYTY2MzNjNjJhMzRjNzIyNWViMzk5ODg0OTcyYTYxMjc4Yzc5MjIyNjRiMWNiNWM0M2UxZjE0YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hoq1CLY53Ubc7CQI0HnhiNbQlL50-mhCACxxJCHgbVI) ](https://private-user-images.githubusercontent.com/63306833/342733559-c84c9e5b-03ba-4737-870c-47554f1ed583.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTkyOTAsIm5iZiI6MTcxOTk5ODk5MCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NTktYzg0YzllNWItMDNiYS00NzM3LTg3MGMtNDc1NTRmMWVkNTgzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA5Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MTZkNjBjYTY2MzNjNjJhMzRjNzIyNWViMzk5ODg0OTcyYTYxMjc4Yzc5MjIyNjRiMWNiNWM0M2UxZjE0YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hoq1CLY53Ubc7CQI0HnhiNbQlL50-mhCACxxJCHgbVI) [ ](https://private-user-images.githubusercontent.com/63306833/342733559-c84c9e5b-03ba-4737-870c-47554f1ed583.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTkyOTAsIm5iZiI6MTcxOTk5ODk5MCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NTktYzg0YzllNWItMDNiYS00NzM3LTg3MGMtNDc1NTRmMWVkNTgzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA5Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MTZkNjBjYTY2MzNjNjJhMzRjNzIyNWViMzk5ODg0OTcyYTYxMjc4Yzc5MjIyNjRiMWNiNWM0M2UxZjE0YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hoq1CLY53Ubc7CQI0HnhiNbQlL50-mhCACxxJCHgbVI)
> 
> ![2024-06-25 15 49 49](https://private-user-images.githubusercontent.com/63306833/342733574-950c7e9b-439c-4769-a353-9e9bf2a90352.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTkyOTAsIm5iZiI6MTcxOTk5ODk5MCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NzQtOTUwYzdlOWItNDM5Yy00NzY5LWEzNTMtOWU5YmYyYTkwMzUyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA5Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MWUzNTRmMjcwZTQxYzlmYWNiYmM1YmVhNTBmYWE3ZGFlYjdjNDU3ZGMxNjhlYzVkNTA4Nzc1MjBmMWEyODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WrJnw7Yv8PeE3udY9JjMZQuzAuQm4f-nopGhM8tLhcc) [ ![2024-06-25 15 49 49](https://private-user-images.githubusercontent.com/63306833/342733574-950c7e9b-439c-4769-a353-9e9bf2a90352.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTkyOTAsIm5iZiI6MTcxOTk5ODk5MCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NzQtOTUwYzdlOWItNDM5Yy00NzY5LWEzNTMtOWU5YmYyYTkwMzUyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA5Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MWUzNTRmMjcwZTQxYzlmYWNiYmM1YmVhNTBmYWE3ZGFlYjdjNDU3ZGMxNjhlYzVkNTA4Nzc1MjBmMWEyODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WrJnw7Yv8PeE3udY9JjMZQuzAuQm4f-nopGhM8tLhcc) ](https://private-user-images.githubusercontent.com/63306833/342733574-950c7e9b-439c-4769-a353-9e9bf2a90352.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTkyOTAsIm5iZiI6MTcxOTk5ODk5MCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NzQtOTUwYzdlOWItNDM5Yy00NzY5LWEzNTMtOWU5YmYyYTkwMzUyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA5Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MWUzNTRmMjcwZTQxYzlmYWNiYmM1YmVhNTBmYWE3ZGFlYjdjNDU3ZGMxNjhlYzVkNTA4Nzc1MjBmMWEyODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WrJnw7Yv8PeE3udY9JjMZQuzAuQm4f-nopGhM8tLhcc) [ ](https://private-user-images.githubusercontent.com/63306833/342733574-950c7e9b-439c-4769-a353-9e9bf2a90352.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTkyOTAsIm5iZiI6MTcxOTk5ODk5MCwicGF0aCI6Ii82MzMwNjgzMy8zNDI3MzM1NzQtOTUwYzdlOWItNDM5Yy00NzY5LWEzNTMtOWU5YmYyYTkwMzUyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA5Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MWUzNTRmMjcwZTQxYzlmYWNiYmM1YmVhNTBmYWE3ZGFlYjdjNDU3ZGMxNjhlYzVkNTA4Nzc1MjBmMWEyODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WrJnw7Yv8PeE3udY9JjMZQuzAuQm4f-nopGhM8tLhcc)
> 
> CC @rkrishnan8594

What is about this issue? how to resolve this @rkrishnan8594

**Comment by Ihor-Karpyn** [comment]
> What is about this issue? how to resolve this

@JaykrishnaArhamlabs Hey, it looks like the team has fixed the issue, and the code in the sandbox is working well.

@rkrishnan8594 Thanks for the help ❤️

**Comment by JaykrishnaArhamlabs** [comment]
> > What is about this issue? how to resolve this
> 
> @JaykrishnaArhamlabs Hey, it looks like the team has fixed the issue, and the code in the sandbox is working well.
> 
> @rkrishnan8594 Thanks for the help ❤️

@Ihor-Karpyn can you please send the code sandbox link so I can test.

**Comment by Ihor-Karpyn** [comment]
@JaykrishnaArhamlabs You can find link to code sand box in this [message](https://github.com/vimeo/player.js/issues/1038#issuecomment-2188856053)
