### ISSUE TITLE
Video not embeddable error

### ISSUE THREAD

**Issue by cjamodeo** [vimeo/player.js#270]
### Expected Behavior
Embed a video on a 4th-level domain with its Privacy set to "Only on sites I choose" and including the 2nd-level domain in the allowed domains list.

### Actual Behavior
Receive a promise error: "https://vimeo.com/xxxxxxxxxx" is not embeddable.

### Steps to Reproduce
1. Set a video's privacy to "Only on sites I choose"
2. Add a 2nd-level domain to the allowed domains list (i.e. domain.com)
3. Embed the video on a 4th-level domain (i.e. 4th.3rd.domain.com)
4. Receive error from ready promise (player.ready())

This appears to occur in embed.js: getOEmbedData. When the JSON data comes back from the request its "domain_status_code" is set to 403 and rejected on line 115.

This behavior did not exist in v2.6.1 and may be related to bug [264](https://github.com/vimeo/player.js/pull/264) 

It seems the only way to correct this in v2.6.2 is to explictly add the 4th-level domain to the allowed domains list. In v2.6.1 adding the 2nd- or 3rd-level domain allowed the video to be embedded on the 4th-level domain.

**Comment by cjamodeo** [comment]
This issue seems to affect more than just ready() and may also affect all player methods and events. For instance, it seems like calling play() produces the same error. Clicking the player's play button seems to play the video, but after doing so the play event is not fired.

**Comment by illiasaveliev** [comment]
Is there any progress on this issue?  Will it be included in the next release? 
We've tried to put 3rd level domain in the account settings, but it didn't help.

**Comment by tenacex** [comment]
@illiasaveliev sorry for the delay. I am going to be looking into this bug today. I will keep you updated. I first need to see if this is expected behavior, as the API team tells me that it is.

**Comment by tenacex** [comment]
@illiasaveliev this is another issue with the new api feature we added. I have confirmed that this is an issue on their end, and it should be fixed soon! Thanks for bringing it to our attention.

**Comment by illiasaveliev** [comment]
@tenacex  thank you for investigation, do you know when the next release of API is planning? or how soon this problem will be fixed?

**Comment by tenacex** [comment]
@illiasaveliev this should be fixed. Thanks for bringing it to our attention.

**Comment by jamierytlewski** [comment]
How was this fixed? We are still having an issue.

**Comment by danielstgt** [comment]
I can confirm that this is still an issue with private videos. Embedding a video brings up the same 404 shown in @jamierytlewski's screenshot.

**Comment by virajsoni06** [comment]
Hi, facing a similar issue. Any update on this?

**Comment by Ravenna** [comment]
I am seeing this issue.  Please update asap.

**Comment by tenacex** [comment]
Hi guys could you please send me a jsfiddle or something with clearer steps to reproduce. I created a private video and I can embed it totally fine with this embed code: http://jsfiddle.net/rzsckpt3/

**Comment by Ravenna** [comment]
I see this issue with these privacy settings.  Hide from Vimeo, and only embeddable on specific domains.  And I am sure those domains are correct.

![screen shot 2018-10-23 at 6 55 30 am](https://user-images.githubusercontent.com/72239/47365618-c98e9700-d690-11e8-8b92-9587869ae8b9.png)

**Comment by tenacex** [comment]
Ok, I need to know the domains to see what is going on. Could you please send an email to dylan@vimeo.com with the domain you have added and I will check.

**Comment by tenacex** [comment]
Thanks for the emails everyone. The clips I was sent were not listed on vimeo.com, so they cannot be instantiated by just passing a clip id. You can instantiate a private clip via the api by doing the following: http://jsfiddle.net/luwes/Lwsc5bya/

I am going to update the docs to explain this.

**Comment by jamierytlewski** [comment]
Out of curiosity, would it be difficult to have something like

```
<div id="player" data-vimeo-id="293438045/463ebf7bcf"></div>
```

That way all the code would be consistent.

**Comment by tenacex** [comment]
@jamierytlewski I agree this could definitely be done better. We are going to be looking into it, I can keep this ticket updated with the info.

**Comment by djiest** [comment]
> 
> 
> Hi guys could you please send me a jsfiddle or something with clearer steps to reproduce. I created a private video and I can embed it totally fine with this embed code: http://jsfiddle.net/rzsckpt3/

For me, your jsfiddle states the video can't be shown because of its settings

**Comment by djiest** [comment]
@luwes thanks for the reply
I've added `jshell.net` to the whitelist. But the video still is not shown, stating that `Because of its privacy settings, this video cannot be played here.`
As pointed out, your example also does not work.

**Comment by luwes** [comment]
http://jsfiddle.net/rzsckpt3/
http://jsfiddle.net/7062g4qj/

these are loading fine on my end in Chrome incognito.
maybe try clearing browser cache or so.

**Comment by djiest** [comment]
Ok, what is the best way to determine what (additional) domain needs to be
whitelisted?

Regards
Joost


Op ma 7 jan. 2019 16:09 schreef wesley luyten <notifications@github.com:

**Comment by luwes** [comment]
In most situations the url in the browser bar will be the one to whitelist.

Very rarely websites use wrapper iframes that have a different domain, it's sites like jsfiddle.net, codepen.io, facebook, linkedin, etc that could have these.

Best way to determine this is to right click on the Vimeo player and choose inspect element, you'll see the html tags. If there is an iframe wrapping the Vimeo player iframe you'll have to add the src url of the wrapping iframe to the whitelist.

Hope this helps a bit.

Best regards, Wesley

**Comment by djiest** [comment]
Hi Wesley,

When I check the video in a browser I never use, the video IS shown. Is
there a way to prevent the caching issue?


Op ma 7 jan. 2019 om 23:34 schreef wesley luyten <notifications@github.com>:

**Comment by luwes** [comment]
To delete cache on Chrome is pretty easy cmd+shift+R.
Others please see https://www.refreshyourcache.com/en/home/

There's multiple ways to accomplish this.

**Comment by djiest** [comment]
Hi Wesley,

I'm familiar with clearing cache in browsers :-).
What I meant if there is a way to prevent the video from being cached. I
think it's strange that changing settings in Vimeo has no effect on the
showing of the video, without clearing the cache.

Regards,
Joost


Op di 8 jan. 2019 om 17:33 schreef wesley luyten <notifications@github.com>:

**Comment by webdevtube** [comment]
I'm having similar issue but I cannot reproduce it.
The reason is I'm not getting error on my own but some of my users are getting this error.

I know that because I catch JS errors and send them to my backend to log file. So I see that some users had in the browser console error saying "https://vimeo.com/xxxxxxxx is not embeddable"

I'm using only 2nd level domain, not the 3rd or above.
The error occur only for some users of my website which uses subdomain. That subdomain is present as one of allowed to embed in domain list in settings of that video.

What can be the problem?

**Comment by morgenfriedel** [comment]
I have this issue as well. The domain and subdomain are explicitly whitelisted in the Vimeo settings for the embedded videos, but there's a JavaScript error when you try to view from the browser that reads:

> Vimeography Error: "https://vimeo.com/23423423" is not embeddable.

Strangely, if I edit the Vimeography galleries, I can see the videos properly embedded on the Edit screen of the dashboard. This leads me to believe it's not the URL or privacy settings within the site or Vimeo. 

The site is using the latest versions of the following plugins:

* Vimeography - 2.0.8
* Vimeography Pro - 2.0.6
* Vimeography Theme:Playlister - 2.0.6

**Comment by wesbos** [comment]
Getting this error too. 

For me I had ~50 videos restricted to wesbos.com AND courses.wesbos.com

When I removed wesbos.com from 1 video, the rest started to work? 

Very weird

**Comment by warrenmcquinn** [comment]
I'm noticing some users receiving this error (via Sentry.io) and I cannot reproduce it myself, despite visiting the same pages as the affected users. 

> “https://vimeo.com/xxxxxxxxxx” is not embeddable.

Using 2.14.1 (latest release). User stories show that the issue is affecting all OS types, but not all users.

Could there be some kind of browser extension that is preventing Vimeo videos from being embedded?

**Comment by jonasfeige** [comment]
Running into this issue as well.
Videos are successfully being loaded on the front-end of a site, but throwing errors in its CMS (where I am using the exact same embed code). There is no other iframe wrapping the one instantiated by player.js, so I don’t know what might be the issue.

**Comment by MikeLawton** [comment]
Getting this error too. All videos were working fine for weeks and have suddenly stopped working

**Comment by MikeLawton** [comment]
Getting this error too. 

All videos have been working fine for weeks and have suddenly stopped working with error: 

`“https://vimeo.com/xxxxxxxxxx” is not embeddable.`

All the videos are private but the domain has been whitelisted in Vimeo.

It's a Gatsby site hosted on Netlify, Vimeo embeds are using [@u-wave/react-vimeo](https://www.npmjs.com/package/@u-wave/react-vimeo). 

All videos still working fine on locally. 

Tried hosting on GatsbyCloud to see whether it was a Netlify specific issue but same issue there too. 

Tried to use native Vimeo iframe embeds too, same issue.

I've reached out to Vimeo but wondered if anyone else has resolved this issue.
