### ISSUE TITLE
Edge - Cuepoints throw exception

### ISSUE THREAD

**Issue by rollinson9** [vimeo/player.js#292]
### Expected Behavior
Cuepoints to console.log when fired

### Actual Behavior
Cuepoints throw error - SCRIPT5022: Exception thrown and not caught

### Steps to Reproduce
[CodePen](https://codepen.io/anon/pen/qyaPjK)

Edge build: Microsoft Edge 42.17134.1.0
Works as expected in all browsers (including IE11)

**Comment by rsichel107** [comment]
Able to reproduce, thanks for logging. We will look into it.

**Comment by ricardodrummond** [comment]
Facing the same problem. Any known workaround?

**Comment by gdau** [comment]
Just want to chime in that having the same issue here on IE 11 too - the api demo site gives the same error too (https://player.vimeo.com/api/demo). If you add a cuepoint, it allows it to be added but raises an exception when the cue point time is reached.

**Comment by luwes** [comment]
Thank you for reporting this issue.

This has been resolved in the latest player release.
Let me know if it's not working on your end or you have any questions.

**Comment by ricardodrummond** [comment]
Hi Luwes,

It's still not working. It's no longer throwing an exception when cuepoint is reached, but it's not firing cuepoint event. 

I've tryed the same script in several browsers, including IE, and it works:

            $(document).ready(function () {

                function markCompleted() {
                    console.log('Cuepoint reached');
                }

                try {
                    var div = document.querySelector('div');
                    var player = new Vimeo.Player(div);

                    player.on('loaded', function () {
                        player.getDuration().then(function (duration) {
                            var cuepoint = 3;
                            player.addCuePoint(cuepoint).then(function () {
                            }).catch(function () {
                            });
                        }).catch(function () {
                        });
                    });
                    player.on('cuepoint', function () {
                        markCompleted();
                    });
                } catch (err) {
                    markCompleted();
                }
            });
