### ISSUE TITLE
TypeError: undefined is not an object (evaluating 't.data.method')

### ISSUE THREAD

**Issue by joker-777** [vimeo/player.js#308]
### Actual Behavior

Without any changes from our site we suddenly can track that our users receive this error `TypeError: undefined is not an object (evaluating 't.data.method')` which is caused in [this line](https://github.com/vimeo/player.js/blob/d953eadc5a82ce46ff48b984e1688210c40f08bd/src/lib/postmessage.js#L65).

### Steps to Reproduce

We can't really reproduce it but we see in our js error tracking system that lots of people are having this error. Have you guys changed anything recently which could be the reason for this error?
We also updated `@vimeo/player` recently but it didn't change anything.

**Comment by rainerborene** [comment]
I can confirm this issue but the error message is a little bit different than yours: `TypeError: Cannot read property 'method' of undefined`

**Comment by rainerborene** [comment]
![not_good](https://user-images.githubusercontent.com/101501/44817843-1ab46a00-abbd-11e8-8412-c384fb3dda7b.PNG)

can't reproduce it either 😢

**Comment by joker-777** [comment]
@rainerborene Yes, we have both error message. It depends on the browser/devise.

**Comment by danaburger** [comment]
links attached below-

http://jsfiddle.net/joker777/sLyco0az/2/ 
https://www.kenhub.com/en/videos/upper-arm-bones-and-ligaments

Note: issue is not reproducible but does come up in logs.

**Comment by joker-777** [comment]
@danaburger Thanks for adding our details. Here some stats about this error from our side.
![screenshot_20180831_165859](https://user-images.githubusercontent.com/378859/44920359-0187f680-ad40-11e8-8019-ee2073bf0d06.jpeg)
Please be aware that we sample the errors we get by 20%. That means we actually only get 20% of all error occurrences. The real numbers are definitely much higher.

**Comment by ilyen85** [comment]
Same error happens on our page also [at the very same line](https://github.com/vimeo/player.js/blob/d953eadc5a82ce46ff48b984e1688210c40f08bd/src/lib/postmessage.js#L65), with the following error message:

`TypeError: Cannot read property 'method' of undefined`

**Comment by reckoner165** [comment]
@joker-777 @rainerborene On error, the API no longer fires postMessages with `data.event === 'error'`, so it's strange that the method would hit those lines while processing an incoming message.  
Can you provide a stack trace from those sentry errors?

**Comment by joaovieira** [comment]
Still happening very often.. is this being looked at? I assume it's an error message from the player iframe, so there's no proper stack trace.

Could we just safe-guard in the `processData` to check for undefined data before accessing the method?

**Comment by danaburger** [comment]
This issue should now be resolved. @joker-777 @joaovieira @rainerborene @ilyen85 are you still seeing errors?

**Comment by joker-777** [comment]
@danaburger The last seen error was at Sep 7, 2018 10:34:37 AM UTC but this could be also related to caching. Let's have a look how it will continue.

May I ask how you resolved this? What was exactly the issue?

**Comment by joker-777** [comment]
@danaburger It doesn't look like that the error is fixed. Do I have to update something?

**Comment by danaburger** [comment]
@joker-777 @joaovieira Sorry to hear the issue is still occurring. To help us get to the bottom of this, could you provide a stack trace around your sentry error logs?

**Comment by rainerborene** [comment]
@danaburger I don't see any change pushed to the master branch.

**Comment by danaburger** [comment]
@rainerborene The push was recorded internally, as we had to make an adjustment our player and not the API. 

If you are still seeing these errors, would you mind providing a stack trace around your error logs? These should help us move forward.

**Comment by rainerborene** [comment]
Just received another notification on Sentry a few minutes ago. It's not fixed yet.

![capture](https://user-images.githubusercontent.com/101501/45337596-3b86a300-b55f-11e8-82da-c78e64ca62ca.PNG)

For now, I'll mute this annoying error directly on Sentry.

**Comment by micahsp** [comment]
I am seeing similar errors starting 08/07/2018 and still present. 
```
TypeError: undefined is not an object (evaluating 'o.data.method')
File https://player.vimeo.com/api/player.js line 2 col 8633 in b
File https://player.vimeo.com/api/player.js line 2 col 10186 in e
```

**Comment by joaovieira** [comment]
Same.

**Comment by rainerborene** [comment]
Same here.

**Comment by jinsoocha** [comment]
Same here

**Comment by hootlex** [comment]
Same.

**Comment by DarosF** [comment]
same

**Comment by mouthzipper** [comment]
same issue

**Comment by Qcasares** [comment]
Same issue

**Comment by worked** [comment]
Same
