### ISSUE TITLE
Video not looping when background is true

### ISSUE THREAD

**Issue by theostrahlen** [vimeo/player.js#349]
### Expected Behavior
Video should loop when ended if `background` is set to `true`

### Actual Behavior
Video autoplays like it should but does not loop.

**Comment by rsichel107** [comment]
Hi @theostrahlen, Thanks for logging the issue. 

If you instantiate the player with the `options` you do have the background problem you describe. We are looking into that and working to fix ASAP. 

As a temporary work-around, you can instantiate this with an iframe and `background` param. https://jsfiddle.net/rebeccas/nmdyLxuw/6/

**Comment by rsichel107** [comment]
This has been fixed in our most recent release. Thank you for logging.

**Comment by bakura10** [comment]
Hi,

Has this been deployed? I'm still having the issue where the video does not loop.

**Comment by rsichel107** [comment]
Yes it has been deployed and works. Here is a JSfiddle example:
https://jsfiddle.net/rebeccas/hm58cLxo/

**Comment by bakura10** [comment]
This is strange,I have one of our customer using our theme. You can see their store here: https://akelasurf.com/ You can see the video at the very end before the footer.

The init code is with those options:

```
id: ID,
autoplay: true,
muted: true,
background: true,
loop: true
```

However the generated URL is as follow: https://player.vimeo.com/video/303743340?muted=1&autoplay=1&background=1&app_id=122963 (no loop attribute).

I've checked and I'm properly using the last player (https://player.vimeo.com/api/player.js). What could cause the URL to be incorrectly generated?

**Comment by rsichel107** [comment]
@bakura10 I can help you with this. Couple things:
1) We are trying to get rid of sending extra parameters so because background = autoplay & muted & loop if someone sends the param `background=1` and also sends the default parameters of autoplay & muted & loop they shouldn't be sent. However, we have only implemented that for loop so far. That is  why you are missing the loop parameter.
2) Background videos are technically only available for our paid users ( https://help.vimeo.com/hc/en-us/articles/115011183028-Embedding-background-videos ) so this video you are using is not on a paid account. Therefore background will not work as intended. 

So in summation, our attempt to optimize the parameters as I describe in point 1 is causing a bug in the case where background is used incorrectly (as you are doing because you can't make that video into a background video). I will discuss with my team whether they think we should change this. 

However, to fix your problem remove the background parameter. This will allow your video to loop however it won't be a true background video because the controls will still be accessible.

**Comment by bakura10** [comment]
Hi !

Thanks for the clarification.

The issue is that we are developing a theme, so we do not control which videos are embedded (some merchants may pay Vimeo Plus, some may not). Do we have a way to check if a video is allowed to use "background" so we can toggle on/off this setting?

I'd argue that Vimeo should take into account the fact that we may not always have the correct information. If background is an invalid setting for some videos, I don't really undersrtand why it would have an impact on another setting that is unrelated (loop). It should simply be ignored.

What do you think?

**Comment by rsichel107** [comment]
Put out a fix. Let me know that it works!

**Comment by bakura10** [comment]
The issue seems to be solved. Thanks a lot :).

**Comment by npruzaniec** [comment]
I am having this issue now. The video loops most of the time fine - but will stop at the end sometimes on the first play - sometimes on subsequent loops. I have also tried with only `background=1` set.

Here is my embed code:
```
<iframe
  src="https://player.vimeo.com/video/894658804?background=1&autoplay=1&loop=1&autopause=0&muted=1"
  class="o-video-autoplay__iframe"
  width="100%"
  height="100%"
  frameborder="0"
  allow="autoplay; encrypted-media"
  role="presentation"
  loading="lazy"
></iframe>
```

Local dev environment.
M1 MacBook Pro
Chrome 120.0.6099.216

**Comment by npruzaniec** [comment]
Seems to be possibly something to do with the settings on the account the above video uploaded to. I have a video from a different account which does not have this problem.

**Comment by npruzaniec** [comment]
Made a new issue: https://github.com/vimeo/player.js/issues/965
