### ISSUE TITLE
Nested promises do not seem to fire

### ISSUE THREAD

**Issue by dotnetgator** [vimeo/player.js#43]
### Steps to Reproduce
The code below is called via an event handler on the player, then tries to do something, perhaps simply writing to the console, once it is sure that the player has been paused.  However, in the case where it is trying to pause the player and then run a callback, the code in the nested promise is never run.
```
player
    .getPaused()
    .then(function (paused) {
        console.info("Was player paused?: " + paused);
        if (paused) {
            // Do something...
            console.info("Doing something interesting.");
        } else {
            // If the player is not paused, pause it first, then do something...
            console.info("Pausing player");
            player
                .pause()
                .then(function () {
                    console.info("Doing something interesting post-pause - this never runs");
                });
        }
    });
```

**Comment by bdougherty** [comment]
If you're doing the same action whether it was previously paused or not, there's no need to check the state. You can do:

```js
player.pause().then(function() {
    console.info('do something interesting');
});
```

If you need to do something different, I would recommend something more like this (nested promises like that aren't really taking full advantage of promises):

```js
player.getPaused.then((function(paused) {
    if (!paused) {
        console.log('pausing player');
        return player.pause();
    }
})
.then(function() {
    console.log('do something interesting');
});
```

If you needed to know which state it was in, you could do:

```js
player.getPaused.then((function(paused) {
    if (!paused) {
        console.log('pausing player');
        return player.pause().then(function() {
            return false;
        });
    }
    
    return true;
})
.then(function(wasPaused) {
    console.log('do something interesting based on the wasPaused state');
});
```

**Comment by dotnetgator** [comment]
Thank you Brad - I looked/am looking into refactoring my approach as you suggested, but so far the results have been mixed.
If I may offer an observation - in your final solution/suggestion, the nested promise you include (eg return player.pause().then...) -- the then part will never fire, and "false" will actually not get returned.

**Comment by bdougherty** [comment]
Oops, there were a couple typos that I've fixed. See an example with it working: http://codepen.io/bdougherty/pen/dXEvEZ

Can you make a CodePen or JSFiddle with your code so I can take a look?

**Comment by bdougherty** [comment]
Closing this. Feel free to comment or reopen if you're still having issues.

**Comment by nicotroia** [comment]
Hello, I'm having a similar issue

My code tries to load a new video and should then autoplay. When I attempt to load a new video however, sometimes the promise will not fire. Here is my sample code...

`// Load and play new video
                        vi_player.loadVideo(mediaId).then(function(id) {
                            // the video successfully loaded
                            // Sometimes this function will not execute....
                            l3d.vi_player.play();
                        }).catch(function(error) {
                            // No errors either...
                            console.log('vi error', error.name);
                        });`

**Comment by nicotroia** [comment]
Follow up: (please let me know if this is off-topic and I can start a new thread)

I hadn't noticed this before, but on the videos that don't load/autoplay, will flash an error briefly in the player. "Unhandled video privacy".

And in the console it says `player.js:7 Refused to load the image 'https://player.vimeo.com/video/152464736' because it violates the following Content Security Policy directive: "img-src https://i.vimeocdn.com https://secure-b.vimeocdn.com https://f.vimeocdn.com https://vimeo.com https://sb.scorecardresearch.com https://ssl.google-analytics.com https://secure.gravatar.com https://i0.wp.com https://i1.wp.com https://i2.wp.com https://f.vimeocdn.com".`

Any idea why this would be happening? Thanks for your help.

**Comment by bdougherty** [comment]
@nicotroia we released a fix for that issue today, let me know if you're still seeing it.

**Comment by nicotroia** [comment]
@bdougherty thank you!

**Comment by paulmolluzzo** [comment]
> @nicotroia we released a fix for that issue today, let me know if you're still seeing it.

@bdougherty I'm still seeing this issue on the first video being loaded when I use the src from the CDN. Steps to reproduce are pretty simple:

```js
player = new Vimeo.Player([some_element]));
player.loadVideo(152464736).then(function(data){ console.log(data)});
```

The example above uses the same video as @nicotroia, but I can reproduce with other video IDs that I have (which are private).

I also see a closely related issue, which is also possibly related to the videos being private:

`player.js:8 Refused to load the image 'https://player.vimeo.com/video/null' because it violates the following Content Security Policy directive: "img-src https://i.vimeocdn.com https://secure-b.vimeocdn.com https://f.vimeocdn.com https://vimeo.com https://sb.scorecardresearch.com https://ssl.google-analytics.com https://secure.gravatar.com https://i0.wp.com https://i1.wp.com https://i2.wp.com https://f.vimeocdn.com".
`

In that error it's saying the video ID is `null`, but it's actually being passed in correctly. (I've even tried hardcoding in an ID to be sure I'm actually loading a real ID.) I'm not sure where it's getting `null` from. My code is below, but if I put a `console.log(data)` inside the `loadVideo().then()` I always see the correct ID being passed back. No errors are coming out of the `catch()`.

```js
myWorkoutPlayer.loadVideo(chosenVideoId).then(function(data) {
  myWorkoutPlayer.getVideoTitle().then(function(data) {
    $('#myWorkoutPlayer .modal-subtitel').text(data);
  });

  var oneIndexedPosition = currentPlaylistposition + 1;
  var updatedWorkoutText = 'My Workout (' + oneIndexedPosition + '/' + customerVideoQueue.length + ')';
  $('#myWorkoutPlayer #modalTitle a').text(updatedWorkoutText);
  return myWorkoutPlayer.play();
}).catch(function(err) {
  console.log(err);
});
```

**Comment by bdougherty** [comment]
@paulmolluzzo does the element you're passing in have a `data-vimeo-id` attribute? If not, that's the reason (and definitely something that should be fixed in the library).

When you first create the player object, either add the `data-vimeo-id` attribute to the element first or pass the id in as the second param:

```js
player = new Vimeo.Player(some_element, {
    id: 152464736
});
```

**Comment by paulmolluzzo** [comment]
@bdougherty Neither of these work. Either separately or in tandem. I've tried from the source and directly in the browser console and still get the same `player.js:8 Refused to load the image 'https://player.vimeo.com/video/null'` error. Any additional advice is appreciated. If I get a chance I'll try to debug with the Vimeo source and move to another issue.

**Comment by bdougherty** [comment]
@paulmolluzzo can you set up a demo page and maybe file a new issue?

**Comment by paulmolluzzo** [comment]
> @paulmolluzzo can you set up a demo page and maybe file a new issue?

In trying to get a working example I think I narrowed down the issue and it's possibly not because of this library but instead some other Vimeo JS. 😄  Specifically, the error is line 8 of [VimeoPlayer - v2.39.3](https://f.vimeocdn.com/p/2.39.3/js/player.js).

The error looks like it's because of the [content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy), not because of the image being `null`. Modifying the CSP on the site didn't correct the error, so I'm starting to think the error is outside of my control entirely. (I'm using this on a Shopify store.)

At this point I'm just gonna drop it. I'm almost entirely sure it has nothing to do with this library. The error is in a different JS file altogether. ¯\_(ツ)_/¯

**Comment by bdougherty** [comment]
@paulmolluzzo I can look into the player issue if you file a new ticket here with a demo. Even if the issue is a CSP issue on another page, it's something helpful for us to know if other people encounter it.
