### ISSUE TITLE
Intermittent buffering (wait spinner) issue in vimeo player

### ISSUE THREAD

**Issue by vijay-singh-16** [vimeo/player.js#544]
We were frequently getting complaints regarding the video buffering (wait spinner) issues. The users usually have very good bandwidth and fairly powerful machines/tabs/smart phones and at the same time when they try some other video streaming platforms like YouTube, Netflix, Amazon Prime Video etc, videos there work absolutely fine.
This problem was intermittent and we were not able to reproduce it in our development setup. But finally we are able to reproduce it.
So, what we found is that Vimeo Player shows wait spinner when it encounters an ERROR SEGMENT(non-downloaded segment) and never tries to download it again. The ERROR SEGMENT can happen when Internet connection breaks or bandwidth reduces during the request from Vimeo Player for the segment. Now even if the Internet connection is stabilized vimeo player keeps on showing the wait spinner because the segment it wants to play is ERROR SEGMENT.
The issue can be easily reproduced by playing any public or private video on vimeo.com website and disconnecting the machine from the Internet for enough time so that the wait spinner appears and then re-connecting to the Internet.

![vimeo](https://user-images.githubusercontent.com/60729120/76733464-e1cfec00-6786-11ea-90ab-30af8864e7bc.jpg)

But on the other hand if we try to do the same with YouTube then the YouTube Player keeps on trying for the ERROR SEGMENT (represented by 'range' variable in the request query string) and whenever it is available video playback resumes. I assume this is a much better approach for handing streaming videos as they are many times played on unreliable/shared Internet connections.

![youtube](https://user-images.githubusercontent.com/60729120/76734575-3ecca180-6789-11ea-87a6-0d05e20e7ccd.jpg)

I tried my best to explain the problem. Hoping to get some solution from the Vimeo team or community members. It will help us a lot and make our customer experience much better in watching videos from Vimeo.

Thanks

**Comment by luwes** [comment]
Thanks for the detailed report @vijay-singh-16.
We are investigating this issue.

How did you block the requests in your tests?

Segment requests are paused in the player when the browser receives an `offline` event, however in your test they seem to continue to be tried.

**Comment by vijay-singh-16** [comment]
> How did you block the requests in your tests?

@luwes In the test environment, we just disabled the wifi of the machine to block the Internet.

**Comment by luwes** [comment]
@vijay-singh-16 could try and reproduce again? we made some changes that should help resolve this issue. thanks

**Comment by vijay-singh-16** [comment]
@luwes Yes. I am still able to reproduce it. Have a look: [screen recording](https://www.youtube.com/watch?v=uQyn6c4cVpA)


Thanks

**Comment by zhjyii** [comment]
Many of our users started reporting same issue recently.
I tried to reproduce it with @vijay-singh-16 's method, but videos play fine for me, they can continue to play automatically when network connection resumes.

@luwes Has this problem already solved by Vimeo? (I saw the latest release was 28 days ago, which doesn't seem to include the fix)

Thanks.

**Comment by vijay-singh-16** [comment]
> I tried to reproduce it with @vijay-singh-16 's method, but videos play fine for me, they can continue to play automatically when network connection resumes.

This is interesting. I am able to reproduce it 10/10 times on different browsers and separate internet connections.
@zhjyii are you following the exact steps shown by me in this [video](https://www.youtube.com/watch?v=uQyn6c4cVpA)?

**Comment by zhjyii** [comment]
@vijay-singh-16 yes, I watched out video again, I think I did the same thing. My test is on Windows Chrome. I will try other machines/browsers, and will post my screen record in case I got something wrong.

**Comment by zhjyii** [comment]
Well, I tried on three Windows Laptops, works on all Chrome, but 100% fail on Firefox (v74.0.1 the latest version) only on one Laptop (clearing cache, disabling firewall won't help).

No problem with Youtube in all cases.

**Comment by zhjyii** [comment]
I also tried iPad (with Safari), because that is most of my customers use.
Result is on an older iPad, I can reliably reproduce the problem, however, on a newer version iPad, the problem always occurs when the video playback just starts, but if jump to the middle of the video and try the same test, it won't happen!

This is the [video ](https://www.youtube.com/watch?v=L0Cx7BHpYu0
) recorded the tests on both iPad.

Again, no problem with Youtube in any of the case.

**Comment by zhjyii** [comment]
@luwes Any progress on this? 
I think this kind of reliability issue is far more important than adding new features. 
With @vijay-singh-16 's method, it is fairly easy to reproduce the issue, I'd be more than happy to help testing, but please investigate the issue.
I got complaints from our customers almost every day!

**Comment by luwes** [comment]
@zhjyii we are currently investigating the issue further. one improvement was released recently which relies on the browser online/offline events but I take that these are not always working reliably across browsers. we will keep you posted on the progress. thanks for reaching out

**Comment by MatthewSaxophone** [comment]
Viewers of my Vimeo videos embedded in my website are also experiencing buffering.  
Comments from these viewers are all along similar lines... "youtube and netflix are fine, but your Vimeo videos are buffering".
At first I thought it was just overloaded internet usage during busy times for specific individuals on cheap internet plans while the whole world is in lockdown.
Now I'm not so sure. 
The comments I'm getting are from users in the USA, and Australia.
Are there any updates to this thread, please ?
Thanks, Matthew

**Comment by shaunsantacruz** [comment]
We're also hearing complaints from our users that they are experiencing excessive buffering. They  report having fast internet connections and that "youtube & netflix etc. play just fine". 

Many Thanks!

**Comment by timgaudion** [comment]
I have the same issue using vimeo on our website, I have just ask a developer to look at this for me and he concluded that the error looks to be with the player, in testing content is being loaded over the network but the player stops after 11 secs and starts buffering and doesn't continue even after everything has been loaded, only after clicking play, pause, and then play again worked for him to start the video playing (refreshing the page doesn't fix it). He suggested if I can't get the issue fixed I could explore detecting when it happens and then fix it by using the API to play/pause/change the playback location (https://developer.vimeo.com/player/sdk/basics) but I'm not sure if this would work as a fix?
Many thanks Tim

**Comment by emcneal** [comment]
I'm also experiencing the same issue with Vimeo and my users are primarily US based users with descent connections. Also Vimeo, you guys should offer the ability to play videos at 144p like YouTube does. Many times the video quality really isn't that important and people are more interested in the audio.

**Comment by paleojoe** [comment]
Just following this thread. I am a communications director and selected Vimeo for our live stream project, but just had a call from someone who heard about the decision. He is taking online education using vimeo and wanted me to know about the buffering issues he's having with it. He has the same conditions as above: US-based; good bandwidth; youtube, etc. work fine; problem is seen on both his iOS and Windows devices, across browsers.

**Comment by douwevdijk** [comment]
HI. We are experiencing the same issue and also a couple of times that the video freezes. Hope something can be done about this as the embedded option is unfortunately unreliable at the moment.

**Comment by andrewsilke** [comment]
I also run a training site with paid Vimeo.  I'm getting a lot of buffering issues, also based in Australia. Tested in Chrome and Explorer/Edge.

**Comment by Dhruv104** [comment]
Same issue, customers can play seemlessly on Netflix, YouTube but not on our website which embeds Vimeo player @luwes  Do you have any update on this?

**Comment by sanjaynainanixlls** [comment]
Well, we also faced the same issue with our users, we have been streaming everyday, since the past 20 days, and our events have around 1000-1200 users on a daily stream and around 5000 users on a weekly stream. And the users have reported buffering and audio stuck issues while playing. To which we contacted the vimeo support, to which they said - "After review of the archive and the logs from our end there unfortunately is nothing to suggest issues from your encoder or from the Vimeo ingest server."

**Comment by fisherinnovation** [comment]
Thank you for all the reports everyone. 

As this repo is specific to the Vimeo Player API, this isn't the optimal location for quality of experience feedback. Although I have copied all this feedback for internal review, I reccomend providing this feedback via our dedicated support channels (https://vimeo.com/help/contact).

Thanks again, your feedback helps us continue to improve!

**Comment by condensed-io** [comment]
@fisherinnovation please elaborate, are you saying the issue was fixed or not?

**Comment by condensed-io** [comment]
also special thanks to @vijay-singh-16 for figuring out how to reproduce a bug that we've been trying to reproduce for a while.

**Comment by fisherinnovation** [comment]
@condensed-io The specific conditions that were reported in this case should be resolved. But pending you are still encountering similar issues with playback please provide feedback via https://vimeo.com/help/contact

**Comment by zhjyii** [comment]
I don't think it fixed. 
I spent half a day to find the way to reproduce the problem and posted video here as to how to make the problem 100% occur on iPad, if you try it now, it still stuck!

**Comment by reconstrukt** [comment]
Hi all,
Chiming in here. We are using the Vimeo player API for a live stream on a website and can confirm this issue persists. 
Similar scenarios to the above: we can reproduce this as a US-based visitor on the latest version of Chrome; if there is a a drop in internet, the player will show an error message and the stream will not restart (unless you refresh the iframe or browser).

**Comment by antropio** [comment]
Another live customer with the same problem, I think is better to track the solution here that is a public space rather than in private channels

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
For most, this is not caused by intermittent connection to the internet, as I believe that http://qr.ae/pvAsLD and my anecdotal testimoney demonstrate, so please re-open this issue.

**Comment by gr3p** [comment]
I have the same problem. However, I might have found a solution by explicitly setting the browser to autoplay policy no user gesture required. Hope this helps someone.
![2022-05-26 10_07_29-Window](https://user-images.githubusercontent.com/5969684/170952730-ef5e66a3-eafc-48b7-aa6b-3877614850d7.png)

**Comment by nicolasrodi** [comment]
Hi, does this issue with vimeo player API was fixed? Anyone use it recently in a embed website?

**Comment by MF-Webdev** [comment]
Hi, I'm using Vimeo for 3 years now and eveything was fine with my embeded video, but suddenly last week, I've started to get users than have this "Hanging" video problem after a couple of seconds of playback ...

I'm searching for a solution too

**Comment by Firsh** [comment]
It started happening to us too in the past few weeks as well!
