### ISSUE TITLE
Non-passive event listener chrome warnings

### ISSUE THREAD

**Issue by megan-parkes-sonocent** [vimeo/player.js#553]
Hi,

We're seeing some warnings appear in chrome when using this module. The warnings are viewable on https://player.vimeo.com/api/demo in chrome v80.

Can the listeners be made passive or are the non passive event listeners required? 
![Screenshot 2020-04-03 at 16 14 50](https://user-images.githubusercontent.com/57533827/78377281-55fff180-75c7-11ea-91ea-496b32cdb931.png)

```
player.js:10 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Kf.addEvent @ player.js:10
Kf.addEvent @ player.js:10
$f @ player.js:10
Kf.on @ player.js:10
Ct @ player.js:10
ov @ player.js:10
(anonymous) @ player.js:10
initializationHandler @ player.js:10
(anonymous) @ player.js:10
player.js:10 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Kf.addEvent @ player.js:10
Kf.addEvent @ player.js:10
$f @ player.js:10
Kf.on @ player.js:10
(anonymous) @ player.js:10
av @ player.js:10
(anonymous) @ player.js:10
initializationHandler @ player.js:10
(anonymous) @ player.js:10
player.js:10 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

**Comment by martinweck** [comment]
+1 I have got those warnings, too. Please fix them:
`[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
player.js:10 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
nl.addEvent @ player.js:10
nl.addEvent @ player.js:10
tl @ player.js:10
nl.on @ player.js:10
Ct @ player.js:10
iv @ player.js:10
(anonymous) @ player.js:10
initializationHandler @ player.js:10
(anonymous) @ player.js:10
player.js:10 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
nl.addEvent @ player.js:10
nl.addEvent @ player.js:10
tl @ player.js:10
nl.on @ player.js:10
(anonymous) @ player.js:10
rv @ player.js:10
(anonymous) @ player.js:10
initializationHandler @ player.js:10
(anonymous) @ player.js:10
player.js:10 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
nl.addEvent @ player.js:10
nl.addEvent @ player.js:10
tl @ player.js:10
nl.on @ player.js:10
Qv @ player.js:10
(anonymous) @ player.js:10
initializationHandler @ player.js:10
(anonymous) @ player.js:10
player.js:10 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
nl.addEvent @ player.js:10
nl.addEvent @ player.js:10
tl @ player.js:10
nl.on @ player.js:10
(anonymous) @ player.js:10
r @ player.js:10
t.fire @ player.js:10
(anonymous) @ player.js:10
t.fire @ player.js:10
play @ player.js:10
play @ player.js:10
play @ player.js:10
g @ player.js:10
(anonymous) @ player.js:10
(anonymous) @ player.js:10
t.fire @ player.js:10
(anonymous) @ player.js:10
play @ player.js:10
(anonymous) @ player.js:10
f.vimeocdn.com/p/3.20.5/js/player.js:10 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
nl.addEvent @ f.vimeocdn.com/p/3.20.5/js/player.js:10
nl.addEvent @ f.vimeocdn.com/p/3.20.5/js/player.js:10
tl @ f.vimeocdn.com/p/3.20.5/js/player.js:10
nl.on @ f.vimeocdn.com/p/3.20.5/js/player.js:10
Ct @ f.vimeocdn.com/p/3.20.5/js/player.js:10
iv @ f.vimeocdn.com/p/3.20.5/js/player.js:10
(anonymous) @ f.vimeocdn.com/p/3.20.5/js/player.js:10
initializationHandler @ f.vimeocdn.com/p/3.20.5/js/player.js:10
(anonymous) @ f.vimeocdn.com/p/3.20.5/js/player.js:10
f.vimeocdn.com/p/3.20.5/js/player.js:10 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
nl.addEvent @ f.vimeocdn.com/p/3.20.5/js/player.js:10
nl.addEvent @ f.vimeocdn.com/p/3.20.5/js/player.js:10
tl @ f.vimeocdn.com/p/3.20.5/js/player.js:10
nl.on @ f.vimeocdn.com/p/3.20.5/js/player.js:10
(anonymous) @ f.vimeocdn.com/p/3.20.5/js/player.js:10
rv @ f.vimeocdn.com/p/3.20.5/js/player.js:10
(anonymous) @ f.vimeocdn.com/p/3.20.5/js/player.js:10
initializationHandler @ f.vimeocdn.com/p/3.20.5/js/player.js:10
(anonymous) @ f.vimeocdn.com/p/3.20.5/js/player.js:10
f.vimeocdn.com/p/3.20.5/js/player.js:10 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
nl.addEvent @ f.vimeocdn.com/p/3.20.5/js/player.js:10
nl.addEvent @ f.vimeocdn.com/p/3.20.5/js/player.js:10
tl @ f.vimeocdn.com/p/3.20.5/js/player.js:10
nl.on @ f.vimeocdn.com/p/3.20.5/js/player.js:10
Qv @ f.vimeocdn.com/p/3.20.5/js/player.js:10
(anonymous) @ f.vimeocdn.com/p/3.20.5/js/player.js:10
initializationHandler @ f.vimeocdn.com/p/3.20.5/js/player.js:10
(anonymous) @ f.vimeocdn.com/p/3.20.5/js/player.js:10
f.vimeocdn.com/p/3.20.5/js/player.js:10 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

**Comment by luwes** [comment]
thanks for the feedback! we will look into this

**Comment by jpowell** [comment]
We've run into this as well. Check this out: https://web.dev/uses-passive-event-listeners/

Seems like an easy fix 🎉

**Comment by abombelli** [comment]
Same issue here.

**Comment by luwes** [comment]
we released a fix with explicit passive properties for the events.
looks like this is resolved 🎉 please let us know if you see any issues

**Comment by brown2020** [comment]
This issue is back with the Vimeo player:

<img width="1285" alt="Screen Shot 2022-07-20 at 8 59 31 AM" src="https://user-images.githubusercontent.com/215157/180028767-31848699-ecef-4b34-8e23-cf4136ba3023.png">

**Comment by Nicholasbell03** [comment]
Can confirm I am receiving the issue with Vimeo player 2.20.1

**Comment by chrish123** [comment]
I can confirm the same issue
![image](https://github.com/vimeo/player.js/assets/409104/5672419a-9a6f-405a-9222-4c7d8051dc8c)

**Comment by alexberdejo7** [comment]
mismo problema

**Comment by MatteoBruschetti** [comment]
Same problem with VimeoPlayer - v4.27.3 - 2024-01-24

**Comment by rkrishnan8594** [comment]
For those still experiencing this issue, could you provide steps for reproduction, as well as a description of the end user impact?
