### ISSUE TITLE
addCuePoint not working in IE

### ISSUE THREAD

**Issue by nickdoherty** [vimeo/player.js#95]
### Expected Behavior
A cuepoint is added.

### Actual Behavior
A cuepoint is not added.

### Steps to Reproduce

Open https://player.vimeo.com/api/demo in IE, try and add some seconds to the addCuePoint field, click the addCuePoint button, watch it error out. Tested on IE10/11/Edge.

**Comment by bdougherty** [comment]
Thanks for reporting this. I've fixed it in the player but it likely won't be deployed until the new year.

**Comment by bdougherty** [comment]
This should be fixed as of January 5. Sorry for not updating this ticket sooner. Let me know if you're still having issues with them.

**Comment by JoshuaGilmer** [comment]
I still see this issue currently using the same steps to reproduce as above. I tested in IE10 on Windows 7. When attempting to add a cuepoint, the following message is logged:

InvalidCuePoint: Unable to add cue point
